Update type for `Item` to include the new `availableQuantity`
And fix the previous commit failed build:
https://master--vtex.myvtex.com/admin/builder-log/build-log-viewer/e3d2a190bd7b434a8b9ef77a3db6fdbb

```
build.status: fail - Webpack build failed.
Webpack for react@3.x builder finished in 3757ms with errors:
[at-loader] ../../.../react/QuantitySelector.tsx:62:26
TS2339: Property 'availableQuantity' does not exist on type 'Item'.
[at-loader] ../../.../react/QuantitySelector.tsx:88:24
TS2339: Property 'availableQuantity' does not exist on type 'Item'.
```